### ISSUE TITLE
How to deal with our two .NET/CSharp Wechaty project

### ISSUE THREAD

**Issue by huan** [wechaty/dotnet-wechaty#4]
Current we have two .NET Wechaty projects related to your issue:

- https://github.com/wechaty/dotnet-wechaty created by @echofool 
- https://github.com/Jesn/dotnet-wechaty created by @Jesn
  - https://github.com/Jesn/dotnet-wechaty-getting-started

It would be great for our community if we can have a plan to make it clear for the developers for how to use our .NET/CSharp Wechaty.

The details are to be discussed. 

Please feel free to let me know if you have any good suggestions @echofool  @Jesn 

Related Issues: https://github.com/wechaty/wechaty/issues/2070

**Comment by huan** [comment]
## Update: We decided to merge the two together!

After a discussion with @echofool and @Jesn on WeChat, we decided that it would be our best choice to merge <https://github.com/Jesn/dotnet-wechaty> to <https://github.com/wechaty/dotnet-wechaty> so that we can keep our codebase simple and focus, and all .Net users will use one dotnet-wechaty.

## Todo-list

- [x] Create @wechaty/dotnet team for maintainers: @echofool @Jesn 
- [x] Merge function code from <https://github.com/Jesn/dotnet-wechaty> to <https://github.com/wechaty/dotnet-wechaty>
- [x] Create `wechaty/dotnet-wechaty-getting-started` repo for dotnet users to easy on boarding

**Comment by Jesn** [comment]
After discussion , .Net Wechaty use native, ABP Wechaty  is not maintained,

dotnet-wechaty-getting-started ==> https://github.com/wechaty/dotnet-wechaty-getting-started

**Comment by Jesn** [comment]
https://github.com/wechaty/dotnet-wechaty-getting-started
